name: depencencies_test_with_pip

on:
  push:
    branches: [ dev ]

jobs:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ ubuntu-latest]
      python-version: ['3.7', '3.8']
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for the considered OS
      run: |
        python -m pip install --upgrade pip
        pip install .
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install cdsapi
        pip install ecmwf-api-client
    - name: Display Python version
      run: python --version